### ISSUE TITLE
Create new FixCoords script, or expand FixTallies

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-etl-script#35]
Over in #34 I diagnosed an issue where lots of crashes in Socrata now have different coordinates than what we have in CARTO. We suspect that NYC might sometimes regeocode crashes with poor location info as they improve their geocoder, but ultimately, we're not sure why this happens.

As a way to patch the problem, we need to develop a script that updates XY coordinates from Socrata into CARTO.

We already have a couple of methods we have used to deal with changes in tallies of injured/killeD:

1. Every day as part of `main.py` we look back 90 days and update tallies. That's here: https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/blob/master/main.py#L814. This runs daily so we can be sure it's correct to current schema and approaches, etc.
1.  We also "FixTallies" script that checks more broadly for changes in injured/killed data and updates CARTO. That's here:
https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/tree/master/fixtallies. This runs manually and we haven't touched it in 2 years. Not sure when we last ran it, so it may or may not work. As I recall, we used this to catch up on wrong injured/killed tallies so we could then do the 90 day update in 1.

Right now, we could have wrong coordinates going all the way back to the beginning, so it seems like we'll need some version of 2, and then include the XY update in our main.py going forward as well.

This [spreadsheet tab](https://docs.google.com/spreadsheets/d/1xY8BD7dWZIF53N8uv5T1Rr-_tJesQOHK5d12BczQ22M/edit#gid=575582412) has a list of known mismatched records, where `COLLISION_ID` is `socrata_id`. 

This is interesting, drawing on a sample of just things around CB107, showing that most of the problem is in 2016:

|Year |  Mismatched Count|
|----|----|
|2021 | 58|
|2020 | 15|
|2019 | 13|
|2018 | 24|
|2017 | 89|
|2016 | 1032|
|2015 | 0|
|2014 | 1|
|2013 | 0|
|2012 | 1|

Bills to `CHEKPEDS:Crashmapper Ongoing`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1109423802232195/1201383580479926)

**Comment by gregallensworth** [comment]
If the 1233 rows listed in the spreadsheet, I see that 1145 of them are in CARTO

Of those, 841 have `the_geom IS NULL` and 304 have a not-null geometry.

**Those with null geometry in CARTO**

The ones which had no geometry at the time they were imported, was (if I recall) a known phenomenon, and now we know that NYC may go back and geocode them. So that's good to know - some 73% of these mismatches should get an update to ADD geometry where we did not have it.

So that will be a clear gain!


**Those with differing geometry from Socrata**

I have added a new **OFF METERS** column, with a Haversine calculation. I'm glad I did, because in my initial random test I grabbed a few that all had <1 meter error, and was about to dismiss this as a cause. But a few are several kilometers!

An extreme example is **socrata_id 3463725, row 1139** in this spreadsheet - the geocode changed by nearly 12 miles!

So in the second part of the script, looking for _changed_ latlong, a potential optimization could be updating only if either coordinate has changed by more than 0.0005. If not, then we would be shifting it by as little as 1 meters... and potentially _updating the same record every day_ due to implicit rounding error as the coordinates are saved.

**Comment by gregallensworth** [comment]
**Those with differing geometry from Socrata**

I have added a new **OFF METERS** column, with a Haversine calculation. I'm glad I did, because in my initial random test I grabbed a few that all had <1 meter error, and was about to dismiss this as a cause. But a few are several kilometers!

An extreme example is **socrata_id 3463725, row 1139** in this spreadsheet - the geocode changed by nearly 12 miles!

So in the second part of the script, looking for _changed_ latlong, a potential optimization could be updating only if either coordinate has changed by more than 0.0005. If not, then we would be shifting it by as little as 1 meters... and potentially _updating the same record every day_ due to implicit rounding error as the coordinates are saved.

- [ ] new ETL script to go over CARTO records `where the_geom is not null`
  - [ ] TBD TBD
  - [ ] TBD TBD
  - [ ] TBD TBD

**Comment by gregallensworth** [comment]
**Those with null geometry in CARTO**

The ones which had no geometry at the time they were imported, was (if I recall) a known phenomenon, and now we know that NYC may go back and geocode them. So that's good to know - some 73% of these mismatches should get an update to ADD geometry where we did not have it. So that will be a clear gain!

- [ ] new ETL script to check over those CARTO records `WHERE the_geom IS NULL`
- [ ] pull Socrata for those records
  - [ ] potentially doing a few dozen records at a time to balance between hundreds of single-record queries, and one query where the "socrata id in (12345, 67890, 5432, 7654321, ...)" is over-length and fails.
- [ ] and update in CARTO

**Comment by gregallensworth** [comment]
**Those absent from CARTO**

The most likely cause, is that these crashes were not entered until after the looking-back period. The looking-back is defined as 2 months.

```
FETCH_HOWMANY_MONTHS = 2  # when looking for new records in SODA, look back how many months?
```

I would need to sit down and narrow down the time window(s) for these missing ones, then run the "backlog" script to pick them up.

- [ ] go over the spreadasheet, find the missing ones and their time windows
- [ ] re-examine the backlog script, see about running it to pick up these crashes

**Comment by gregallensworth** [comment]
Refreshing my memory too:

The **fixtallies** script was not an automated CARTO-and-Socrata checking tool. It accepted two CSV files of data dumps from the two, so went into it looking for a known universe of incorrect tallies as determined by visual & mental examination.

**Comment by danrademacher** [comment]
One open loop here is whether there's any way to make the `latlng` updates part of our scheduled script updates in `main.py`  that run every day. Even though those would only run on the 90-day "lookback" it seems like this would be a good improvement to make to stay a bit more aligned with Socrata.

**Comment by gregallensworth** [comment]
> any way to make the latlng updates part of our scheduled script updates in `main.py` that run every day
> those would only run on the 90-day "lookback"

The 90 days back is for fetching new records not yet in CARTO, not to (in addition to its job of finding new crashes) fetch those thousands of crashes and run a point-by-point comparison. By definition, a newly-found crash matches the geometry found in that selfsame newly-found crash, and would not be useful.

What you're asking for here would be a _third script_ to run via Heroku Scheduler (main for crashmapper, and there's one for walkmapper), not an extension to `main.py` It'll be the same process I spent a few days developing and running, but for a shorter range and without an intermediate CSV for validation, and running quickly enough that it could run, say, weekly.

- [ ] find the current date minus 90 days
- [ ] find crashes in both sides since then
  - [ ] find the cartodb_id, socrata_id, latitude, longitude, geom of all crashes in CARTO during that period
  - [ ] find all crashes in SODA corresponding to those same crashes (`socrata_id = collision_id`)
  - [ ] iterate over all of those pairs, the make_diffs_csv programming, and find diffs > 15 meters
- [ ] compose list of SQL queries to update the geometry fields (3) and null out the polygon fields (8). The polygon fields will get picked up the next day by main.py
  - [ ] the_geom
  - [ ] latitude
  - [ ] longitude
  - [ ]  borough
  - [ ] city_council
  - [ ] senate
  - [ ] assembly
  - [ ] businessdistrict
  - [ ] community_board
  - [ ] neighborhood
  - [ ] nypd_precinct
- [ ] submit this list of queries to the batch API

**Comment by danrademacher** [comment]
Hmm, OK, I thought this section of `main.py` went back and updated the killed and injured tallies and maybe we could do something similar for `xy`:
https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/blob/master/main.py#L871-L927

But I gotta admit that code is at the edge of my understanding, so if a separate script is better, that's fine.
