### ISSUE TITLE
Redistricting Assembly and City Council districts

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper-etl-script#38]
- [x] Locate new SHP for City Council (Dan)
- [x] Locate new SHP for State Assembly (Dan)
- [x] Confirm same schema as in Carto (Dan)
- [x] Upload new tables to CARTO (Dan)
- [x] Develop script to reassign all crashes to new districts, based on https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/tree/master/initialpolygonlinkage (Gregor)
- [ ] 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1109423802232195/1203777890402605)

**Comment by danrademacher** [comment]
# Assembly
Here's the current data on carto, https://chekpeds.carto.com/tables/nyc_assembly/map, clearly clipped to shoreline:
![image](https://user-images.githubusercontent.com/1423200/215908526-5ceb6c5c-7d92-47e0-bde2-85a247cb22ea.png)

* GeoJSON: https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_State_Assembly_Districts/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson
* REST and metadata: https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_State_Assembly_Districts/FeatureServer/0

Looks like the data on Carto has a field with "Assembly District " concatenated onto the integer, so we'd need to do that when we make the new data.

# City Council
Hmm, the current City Council data on Carto is a bit weird: https://chekpeds.carto.com/tables/nyc_city_council

Pretty weird ID here:
![image](https://user-images.githubusercontent.com/1423200/215910603-607d572d-ebb9-4b85-a3db-9471322cd895.png)

New data:
* GeoJSON: https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_City_Council_Districts/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson
* REST and metadata: https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_City_Council_Districts/FeatureServer/0

**Comment by danrademacher** [comment]
Actually, I think those other fields don't matter so long as `identifier` exists as a bare integer:
https://github.com/GreenInfo-Network/nyc-crash-mapper/blob/26b97a276d2f207469f428739fac80416ea6bdd6/src/constants/sql_queries.js#L27-L34
https://github.com/GreenInfo-Network/nyc-crash-mapper/blob/26b97a276d2f207469f428739fac80416ea6bdd6/src/constants/sql_queries.js#L67-L75

then the labels happen here:
https://github.com/GreenInfo-Network/nyc-crash-mapper/blob/26b97a276d2f207469f428739fac80416ea6bdd6/src/constants/app_config.js#L55-L62

**Comment by danrademacher** [comment]
* New assembly: https://chekpeds.carto.com/tables/nyc_assembly_2023
* New city council: https://chekpeds.carto.com/tables/nyc_city_council_2023

So we should be ready for this hardest checkbox:
- [ ] Develop script to reassign all crashes to new districts, based on https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/tree/master/initialpolygonlinkage (Gregor)

Since that could be a long running process and we don't want to feel under pressure to get it done while we're changing live data, here's my proposal:
1. Leave the new boundary tables in their current state with `_2023` appended to the names
2. In https://chekpeds.carto.com/tables/crashes_all_prod, create new `assembly_2023` and `city_council_2023` fields
3. Target those fields for the reassignment script
4. Test in a feature branch in frontend applications using the new `_2023` geom tables and `assembly_2023` and `city_council_2023` fields
5. Once we are satisfied, we merge in the changes and deploy, then rename the old tables and fields to have `_2018` suffixes

that will leave things in a clear state, but also make it easy to roll back if there's some problem with the assignments. 

At some later date when we're satisfied (or even next year if we want to leave it for a while), we could delete the old _2018 tables and fields.

**Comment by gregallensworth** [comment]
**DRAFT work in progress as I suss things out**

New tables:
https://chekpeds.carto.com/tables/nyc_assembly_2023/public
https://chekpeds.carto.com/tables/nyc_city_council_2023/public

I recall too that the field name in crashes is hardcoded to the name of the area, e.g. the `city_council` visualization/selection implicitly uses the `city_council` field from crashes, so using the field name `city_council_2023` means changing that name globally throughout. So there will likely be steps I don't know yet...

- [ ] assembly table at CARTO https://chekpeds.carto.com/tables/nyc_assembly_2023/public
  - [ ] rename field `assemdist` to `identifier`
  - [ ] create `id` field with string name `CONCAT('Assembly District ', identifier)` Not clear that this field is used, but makes for consistent and readable data
- [ ] city council table at CARTO
  - [ ] update `id` field with string name `CONCAT('City Council District ', identifier)` Not clear that this field is used, but makes for consistent and readable data
- [ ] get frontend working on my PC, usually takes some doing
- [ ] change frontend to use new tables
  - [ ] change `cartoTables` table names in **app_config.js** to use **nyc_assembly_2023** and **nyc_city_council_2023**
  - [ ] global search-replace for `city_council` since table name == field name == label name =and so on
    - [ ] four places in https://github.com/GreenInfo-Network/nyc-crash-mapper/search?q=city_council
  - [ ] global search-replace for `assembly ` since table name == field name == label name =and so on
    - [ ] four places in https://github.com/GreenInfo-Network/nyc-crash-mapper/search?q= assembly
  - [ ] visible difference, Assembly: visual in maps, still has same number of districts
  - [ ] visible difference, Council: visual in maps, still has 51 distinct districts named 1-51
- [ ] `crashes_all_prod` create new fields
  - [ ] `assembly_2023`
  - [ ] `city_council_2023 fields`
- [ ] populate these fields
  - [ ] modify initialpolygonlinkage script https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/tree/master/initialpolygonlinkage to do only these 2 fields
  - [ ] and to use the new tables
  - [ ] and to populate the new fields

Then give everything a test, and see what we think. We know that some counts already do not match due to NYC retroactively changing past data, so not sure how we'll QC this. Maybe just seeing that the same proportion of crashes have `assembly is null` and that a few have changed `assembly != assembly_2023` ?

**Comment by gregallensworth** [comment]
NOTED during testing:

**Invalid geometries in the city council districts were causing tallies to match.** Citywide would seem to work, then I could bring up City Council District and see them. But upon clicking _some of them_ no crash points would display. Upon clearing the specific area selection, the districts would appear back on the map BUT would show visible gaps where no crashes were present, but previously were.

```
-- 17 were bad
SELECT COUNT(*) FROM nyc_city_council_2023 WHERE NOT ST_ISVALID(the_geom)

-- fixed
UPDATE nyc_city_council_2023 SET the_geom = ST_MAKEVALID(the_geom) WHERE NOT ST_ISVALID(the_geom)

-- fixed! and working
SELECT COUNT(*) FROM nyc_city_council_2023 WHERE NOT ST_ISVALID(the_geom)
```

The `nyc_assembly_2023` table did not have invalidities, and seemed to work fine all along.

**Comment by gregallensworth** [comment]
**Code changes ultimately were confined to a single file**

Ultimately, the only code changes required for the frontend to use the new districts, were the table definitions: **src/constants/app_config.js** `cartoTables`

Crashes _do_ have fields for `assembly` `city_council` `borough` et al, but in fact `filterByIdentifierWhereClause()` is only used for intersections and boroughs. All other cases use a runtime spatial join, and there's a note that boroughs are an exception due to timing out.

So the frontend changes are super simple: a two-line patch. Arguably, the two new fields on `crashes_all_prod` for `assembly_2023` and `city_council_2023 fields` is optional, since nothing is using them... except downloads for offline analysis.

**Comment by gregallensworth** [comment]
**I have started running the updates**

Turns out the **initialpolygonlinkage** script really was made for exactly this, and I left good documentation. Doing it in blocks of 2000 crashes at a time, this is 102000 queries

- [ ] City Council
  - **211401** records have city_council = null. Assuming these boundaries have not expanded nor contracted, this same number should still fall outside any city council district.
  - a certain number should show a change, especially where districts had big changes e.g. `SELECT COUNT(*) FROM crashes_all_prod WHERE city_council != city_council_2023`
  - Result
    - XXXGDATBD have null city_council_2023
    - XXXGDATBD have null city_council_2023 != city_council
- [ ] Assembly
  - **205368** records have assembly = null. Assuming these boundaries have not expanded nor contracted, this same number should still fall outside any city council district.
  - a certain number should show a change, especially where districts had big changes e.g. `SELECT COUNT(*) FROM crashes_all_prod WHERE assembly != assembly_2023`
  - Result
    - XXXGDATBD have null assembly_2023
    - XXXGDATBD have null assembly_2023 != assembly

**Comment by gregallensworth** [comment]
```
-- overall counts
-- about 205K crashes never fit into any Assembly nor City Council district
-- and that has not changed much

SELECT COUNT(*) FROM crashes_all_prod WHERE city_council_2023 IS NULL
207,512

SELECT COUNT(*) FROM crashes_all_prod WHERE city_council IS NULL
211,578

SELECT COUNT(*) FROM crashes_all_prod WHERE assembly_2023 IS NULL
205,954

SELECT COUNT(*) FROM crashes_all_prod WHERE assembly IS NULL
205,540
```

**Comment by danrademacher** [comment]
Ok, based on the above, I think we're ready to deploy these changes, though I just realized that we might have to make changes in https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view as well for the new tables. I am honestly not sure if it duplicates the spatial queries from the map application is https://github.com/GreenInfo-Network/nyc-crash-mapper, which would mean code changes in both places, or not

**Comment by gregallensworth** [comment]
Digging into the 450ish crashes that don't fit. It seems to be edge effects, as expected. There are slight differences in the polygon datasets, as you can see below, which really do cause the crash-points to be excluded in 2023 when they were included in 2015. Judging by the Measure Line tool in QGIS, the difference between the datasets is typically under 1 meter, but this is enough when the crash was exactly on an edge.

```
-- exported these mismatches as GeoJSON
SELECT cartodb_id, ST_X(the_geom) AS lng, ST_Y(the_geom) AS lat FROM crashes_all_prod WHERE city_council_2023 IS NULL AND city_council IS NOT NULL
SELECT cartodb_id, ST_X(the_geom) AS lng, ST_Y(the_geom) AS lat FROM crashes_all_prod WHERE assembly_2023 IS NULL AND assembly IS NOT NULL
```

### Overview

![image](https://user-images.githubusercontent.com/3117633/218527807-3c761fed-cd9c-4b43-a8e8-f8a4cd952a3c.png)

### Assembly 2023

![image](https://user-images.githubusercontent.com/3117633/218528382-6ae5d2ae-73c0-44c0-96bd-c7b7b87858d9.png)


### Assembly 2015

![image](https://user-images.githubusercontent.com/3117633/218528461-4f28f752-9ff5-4d8a-9031-70bd23b32e4a.png)

### City Council 2023

![image](https://user-images.githubusercontent.com/3117633/218528772-94bd7346-4b36-437d-8215-a12fcd826563.png)


### City Council 2015

![image](https://user-images.githubusercontent.com/3117633/218528878-bf97b45b-7791-4524-ab9b-9083ca15f72d.png)


### A Measurement Example

![image](https://user-images.githubusercontent.com/3117633/218529843-c18ef482-5515-42f4-a981-d3de4af037dc.png)


### Proposal

I could do a second pass to update any crashes `where city_council_2023 IS NULL and city_council IS NOT NULL` but this time with a buffer of 3 meters (10 feet) on the crashes. This should mop up the majority of these 450 outliers.

**Comment by gregallensworth** [comment]
Several hours later, running scripts to buffer polygons by 0.00002 degrees (about 2 meters) and having CARTO repeatedly time out, or falsely report 0 hits, I gave up on the old methods. I sat down with QGIS and made up lists of cartodb_id and City Council / Assembly identifier, then made up a list of SQL statements to run.

Eventually, we now have only 1 record where `assembly_2023` and `city_council_2023` are null but `assembly` and `city_council` are null. And that's because CARTO will time out updating this one specific record.

```
-- this one row will not let me update it; CARTO SQL API and web UI time out
UPDATE crashes_all_prod SET city_council_2023 = 32 WHERE cartodb_id=1209236
UPDATE crashes_all_prod SET assembly_2023 = 23 WHERE cartodb_id=1209236
```

So, not counting this 1 record, the new assignments are done and the fields & tables could be swapped into place. See the "then some day, swap them" checklist item above.

**Comment by gregallensworth** [comment]
All set! I have renamed the columns and the fields, and the mapper and chart view are using the new districts.

**Comment by danrademacher** [comment]
With #39 resolved this is done

**Comment by danrademacher** [comment]
Also for the record, I suggested we do Senate and she said she doesn't care about those. (Why are they in the tool?) But whatevs -- also was reminded that 2022 NYS redistricting was a shitshow so possibly senate reverted to old lines.
